using Microsoft.Data.SqlClient;

namespace Yagura.Storage.SqlServer;

/// <summary>
/// <see cref="SqlException"/> を database.md §1.2 契約 3 の 3 分類
/// （<see cref="LogStoreFailureKind"/>）へ写像する（<see cref="Sqlite.SqliteFailureClassifier"/> と対）。
/// </summary>
/// <remarks>
/// <para>
/// 対応表の出典は Microsoft Learn「Database Engine events and errors」の該当ページ
/// （confirmed = 本クラス作成時に公式ページを直接確認した日）。<see cref="SqlException.Number"/> は
/// SQL Server が返すエラー番号（<see cref="SqlError.Number"/> の集約。SqlException 公式ドキュメント
/// "Number" プロパティの記載どおり。確認日 2026-07-05）。
/// </para>
/// <para>
/// | エラー番号 | 意味（Microsoft Learn 公式） | Severity | 本分類 | 出典ページ |
/// |---|---|---|---|---|
/// | 1105 | "Could not allocate space for object '%.*ls'%.*ls in database '%.*ls' because the '%.*ls' filegroup is full." | 17 | CapacityExhausted | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-1000-to-1999（確認日 2026-07-05） |
/// | 9002 | "The transaction log for database '%ls' is full due to '%ls'." | 17 | CapacityExhausted | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-9000-to-9999（確認日 2026-07-05） |
/// | 1205 | "Transaction (Process ID %d) was deadlocked on %.*ls resources with another process and has been chosen as the deadlock victim. Rerun the transaction." | 13 | Transient（再試行に意味がある——公式メッセージ自体が "Rerun the transaction" と明記） | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-1000-to-1999（確認日 2026-07-05） |
/// | 1222 | "Lock request time out period exceeded." | 16 | Transient（ロック競合。再試行で解消し得る） | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-1000-to-1999（確認日 2026-07-05） |
/// | 4060 | "Cannot open database "%.*ls" requested by the login. The login failed." | 11 | Permanent（DB 不在・接続時権限不足。設定の問題） | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-4000-to-4999（確認日 2026-07-05） |
/// | 18456 | "Login failed for user '%.*ls'.%.*ls%.*ls" | 14 | Permanent（資格情報・権限の問題。再試行しても解消しない） | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-18000-to-18999（確認日 2026-07-05） |
/// | 229 | "The %ls permission was denied on the object '%.*ls', database '%.*ls', schema '%.*ls'." | 14 | Permanent（権限不足） | learn.microsoft.com/sql/relational-databases/errors-events/database-engine-events-and-errors-0-to-999（確認日 2026-07-05） |
/// </para>
/// <para>
/// <b>上記以外（未知のエラー番号）の分類方針</b>: <see cref="SqlException.Class"/>（Severity）で
/// 安全側に分類する。SqlException 公式ドキュメントの Remarks
/// （learn.microsoft.com/dotnet/api/microsoft.data.sqlclient.sqlexception。確認日 2026-07-05）:
/// "Severity levels from 11 through 16 are generated by the user, and can be corrected by the
/// user. Severity levels from 17 through 25 indicate software or hardware errors." との記載に基づき、
/// Severity 17 以上（ソフトウェア/ハードウェア障害）は <see cref="LogStoreFailureKind.Permanent"/>、
/// 11〜16（利用者側で訂正可能——多くは一時的な状態や入力起因）は状況を絞れないため安全側で
/// <see cref="LogStoreFailureKind.Permanent"/> として扱う。<b>未知コードを Transient に倒すと、
/// 恒久障害を無限リトライへ押し流す害の方が大きい</b>という判断は
/// <see cref="Sqlite.SqliteFailureClassifier"/> の IOERR 方針と同じである。接続断・タイムアウト等の
/// 明確に一時的な事象は、SqlException.Number ではなく <see cref="System.Data.Common.DbException"/>
/// 由来の <c>-2</c>（コマンドタイムアウト）等を個別に追加する拡張余地を残すが、v0.1 時点で確実に
/// 出典確認できた上記 7 番号のみを表に含める。
/// </para>
/// <para>
/// <b>4060（CannotOpenDatabase）の Permanent 分類は安全側判断であり、実際には 2 系統の原因が
/// 同一番号に重なる</b>（コードレビューで指摘・確認済み）: (a) データベース不在（設定・DBA 作業漏れ。
/// 恒久）、(b) ログインの CONNECT 権限がまだ反映されていない一時的な状態（権限付与直後の
/// キャッシュ未更新等。理論上は一時的）。両者を SqlException.Number だけで区別する手段がないため、
/// 上記「未知コードは安全側」と同じ理由で Permanent へ寄せる——(b) を Transient と誤分類し
/// 無限リトライへ落とす害の方が、(a) を Permanent 扱いして早期に警告する保守的な挙動より大きいと
/// 判断した。<see cref="SqlServerLogStore.BuildSchemaPermissionException"/> の提示 SQL は
/// この二重原因を踏まえ、データベース不在の場合の <c>CREATE DATABASE</c> 手順も含める。
/// </para>
/// </remarks>
internal static class SqlServerFailureClassifier
{
    // Microsoft Learn "Database Engine events and errors" 公式ページの番号（確認日 2026-07-05）。
    private const int FilegroupFull = 1105;
    private const int TransactionLogFull = 9002;
    private const int DeadlockVictim = 1205;
    private const int LockRequestTimeout = 1222;
    private const int CannotOpenDatabase = 4060;
    private const int LoginFailed = 18456;
    private const int PermissionDenied = 229;

    // SqlException 公式ドキュメント Remarks の Severity 境界（確認日 2026-07-05）。
    private const byte SoftwareOrHardwareErrorSeverityThreshold = 17;

    public static LogStoreFailureKind Classify(SqlException exception)
    {
        ArgumentNullException.ThrowIfNull(exception);

        return exception.Number switch
        {
            FilegroupFull or TransactionLogFull => LogStoreFailureKind.CapacityExhausted,
            DeadlockVictim or LockRequestTimeout => LogStoreFailureKind.Transient,
            CannotOpenDatabase or LoginFailed or PermissionDenied => LogStoreFailureKind.Permanent,
            _ => LogStoreFailureKind.Permanent,
        };
    }

    /// <summary>
    /// 権限不足の書き込み失敗（<see cref="PermissionDenied"/>・<see cref="LoginFailed"/>・
    /// <see cref="CannotOpenDatabase"/>）かどうかを判定する。スキーマ管理（<see cref="SqlServerLogStore.InitializeAsync"/>）が
    /// <see cref="SchemaPermissionException"/> を送出すべきかの判定に用いる（database.md §5.2）。
    /// </summary>
    public static bool IsPermissionFailure(SqlException exception)
    {
        ArgumentNullException.ThrowIfNull(exception);

        return exception.Number is PermissionDenied or LoginFailed or CannotOpenDatabase;
    }

    public static LogStoreWriteException ToLogStoreWriteException(this SqlException exception, string operationDescription)
    {
        ArgumentNullException.ThrowIfNull(exception);

        var failureKind = Classify(exception);
        var message = failureKind switch
        {
            LogStoreFailureKind.CapacityExhausted =>
                $"{operationDescription}: SQL Server の容量が枯渇しました (SqlErrorNumber={exception.Number})。",
            LogStoreFailureKind.Transient =>
                $"{operationDescription}: 一時的な競合により失敗しました (SqlErrorNumber={exception.Number})。",
            _ =>
                $"{operationDescription}: 恒久的な障害により失敗しました (SqlErrorNumber={exception.Number}, Severity={exception.Class})。",
        };

        return new LogStoreWriteException(failureKind, message, exception);
    }
}
